export var EMessage = {
    CHECK_PETAIN: 'IS_PETAIN_NET_OPEN',
    PLAY_MUSIC: 'IS_PLAYING_MUSIC',
    PTNET_CURRENT_TAB: "GET_PTNET_CURRENT_TAB",
    
    MEDIA_INFO: 'MEDIA_INFOS',
    ALL_TAB_URLS: 'GET_ALL_TAB_URLS',
    CURRENT_TAB_URL: 'GET_CURRENT_TAB_URL',
    TABS: 'GET_TABS',
    TABS_TITLE: 'GET_TABS_TITLE',
    DEBUG: 'DEBUG',
}